name: Fly Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group
    outputs:
      deploy_condition: ${{ steps.set_condition.outputs.condition }}
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Set deployment condition
        id: set_condition
        run: |
          CONDITION=false
          MESSAGES=$(jq -r '.[].message' <<< "${{ toJson(github.event.commits) }}")
          for msg in $MESSAGES; do
            if [[ "$msg" == *"release"* ]]; then
              CONDITION=true
            fi
          done
          echo "condition=$CONDITION" >> $GITHUB_OUTPUT

      - name: Deploy to Fly
        if: ${{ github.event_name == 'push' && steps.set_condition.outputs.condition == 'true' }}
        run: flyctl deploy --remote-only --yes
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

  tag_release:
    name: Tag Release
    needs: deploy
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && needs.deploy.outputs.deploy_condition == 'true'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.64.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: false
